name: recommender
services:
  backend:
    build: ./backend
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - ENV=debug
      - BEDROCK_LLM_ID=mistral.mixtral-8x7b-instruct-v0:1
      - BEDROCK_USE_GUARDRAIL=false
      - BEDROCK_GUARDRAIL_ID
      - BEDROCK_GUARDRAIL_VERSION
    ports:
      - "8000:8000"
